import type { AlertState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: AlertState, fileName = "alert"): ExportPayload {
  return { fileName: `${fileName || "alert"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: AlertState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
    "",
    "function resolveFont(s) { return s.fontBucket === \"google\" ? '\"' + s.googleFontFamily + '\", sans-serif' : \"inherit\"; }",
    "function buildShadow(s) { if (!s.shadowEnabled) return \"none\"; var hex = Math.round(s.shadowOpacity * 255).toString(16).padStart(2, \"0\"); return s.shadowX + \"px \" + s.shadowY + \"px \" + s.shadowBlur + \"px \" + s.shadowSpread + \"px \" + s.shadowColor + hex; }",
    "function severityColor(s) { if (s.severity === \"success\") return s.successColor; if (s.severity === \"warning\") return s.warningColor; if (s.severity === \"error\") return s.errorColor; return s.infoColor; }",
    "function severitySurface(s, kind) {",
    "  const map = { info: { bg: s.infoBg, border: s.infoBorderColor }, success: { bg: s.successBg, border: s.successBorderColor }, warning: { bg: s.warningBg, border: s.warningBorderColor }, error: { bg: s.errorBg, border: s.errorBorderColor } };",
    "  const entry = map[s.severity];",
    "  if (!entry) return kind === \"bg\" ? s.background : s.border;",
    "  return kind === \"bg\" ? entry.bg : entry.border;",
    "}",
    "",
    "const SEVERITY_META = {",
    "  info: { label: \"Information\", icon: \"i\" },",
    "  success: { label: \"Success\", icon: \"+\" },",
    "  warning: { label: \"Warning\", icon: \"!\" },",
    "  error: { label: \"Error\", icon: \"!\" },",
    "};",
    "",
    "export default function AlertComponent() {",
    "  const meta = SEVERITY_META[state.severity] || SEVERITY_META.info;",
    "  const accent = state.accent || severityColor(state);",
    "  const isAssertive = state.role === \"alert\" || state.livePoliteness === \"assertive\";",
    "  const isDismissed = state.previewState === \"closed\";",
    "  const [actionHover, setActionHover] = React.useState(false);",
    "  const [dismissHover, setDismissHover] = React.useState(false);",
    "  const sevBorder = severitySurface(state, \"border\");",
    "  const variantBg = state.alertVariant === \"filled\" ? severitySurface(state, \"bg\") : (state.disabled && state.disabledUseCustomColors ? state.disabledBg : state.background);",
    "  const variantBorderColor = state.alertVariant === \"filled\" || state.alertVariant === \"outlined\" ? sevBorder : (state.disabled && state.disabledUseCustomColors ? state.disabledBorder : state.border);",
    "  const variantBorderWidth = state.alertVariant === \"outlined\" ? Math.max(2, state.borderWidth) : state.borderWidth;",
    "  const iconEl = state.iconMode !== \"none\" ? <span aria-hidden=\"true\" style={{ display: \"grid\", placeItems: \"center\", width: state.iconSize + 24, height: state.iconSize + 24, flexShrink: 0, borderRadius: 16, border: \"1px solid \" + accent, color: accent, background: \"color-mix(in oklab, \" + accent + \" 16%, transparent)\", fontWeight: 900, fontSize: state.iconSize }}>{meta.icon}</span> : null;",
    "",
    "  if (isDismissed) {",
    "    return <div role=\"status\" aria-live=\"polite\" style={{ border: \"1px solid \" + state.border, borderRadius: 16, color: state.muted, fontFamily: resolveFont(state), padding: \"12px 16px\" }}>Alert dismissed.</div>;",
    "  }",
    "",
    "  return (",
    "    <section",
    "      id={state.id}",
    "      role={state.role}",
    "      aria-label={state.ariaLabel}",
    "      aria-live={state.livePoliteness}",
    "      aria-atomic=\"true\"",
    "      tabIndex={state.disabled ? -1 : state.tabIndex}",
    "      data-severity={state.severity}",
    "      data-placement={state.placement}",
    "      data-auto-dismiss={state.autoDismiss}",
    "      style={{",
    "        width: state.width,",
    "        minHeight: state.height,",
    "        padding: state.padding,",
    "        borderRadius: state.radius,",
    "        border: variantBorderWidth + \"px \" + state.borderStyle + \" \" + variantBorderColor,",
    "        borderLeft: state.alertVariant === \"left-accent\" ? \"4px solid \" + sevBorder : undefined,",
    "        boxShadow: buildShadow(state),",
    "        background: variantBg,",
    "        color: state.foreground,",
    "        fontFamily: resolveFont(state),",
    "        opacity: state.disabled ? (state.disabledOpacity ?? 0.5) : 1,",
    "        cursor: state.disabled ? state.disabledCursor : undefined,",
    "        transition: state.transitionDuration > 0 ? \"opacity 0.2s ease, transform 0.2s ease\" : \"none\",",
    "      }}",
    "    >",
    "      <div style={{ display: \"grid\", gap: state.gap }}>",
    "        <div style={{ display: \"flex\", alignItems: \"flex-start\", gap: 16 }}>",
    "          {state.iconPosition === \"left\" ? iconEl : null}",
    "          <div style={{ display: \"grid\", gap: 8, flex: 1, minWidth: 0 }}>",
    "            <p style={{ margin: 0, color: accent, fontSize: 12, fontWeight: 800, letterSpacing: \"0.16em\", textTransform: \"uppercase\" }}>{state.label || meta.label}</p>",
    "            <h3 style={{ margin: 0, fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h3>",
    "            <p style={{ margin: 0, color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "          </div>",
    "          {state.iconPosition === \"right\" ? iconEl : null}",
    "          {state.dismissible ? <button type=\"button\" aria-label=\"Dismiss alert\" disabled={state.disabled} onMouseEnter={() => setDismissHover(true)} onMouseLeave={() => setDismissHover(false)} style={{ border: \"1px solid \" + state.dismissBorder, borderRadius: 12, padding: \"8px 12px\", background: dismissHover ? state.dismissHoverBg : \"transparent\", color: dismissHover ? state.dismissHoverColor : state.dismissColor }}>x</button> : null}",
    "        </div>",
    "        <p style={{ margin: 0, border: \"1px solid \" + state.border, borderRadius: 16, padding: \"12px 16px\", color: state.muted, fontSize: state.bodySize }}>{state.helper} {isAssertive ? \"Assertive announcement.\" : \"Polite announcement.\"}{state.autoDismiss ? \" Auto-dismiss in \" + state.autoDismissDuration + \"ms.\" : \"\"}</p>",
    "        {state.showActions ? <div style={{ display: \"flex\", flexWrap: \"wrap\", gap: 12 }}><button type=\"button\" disabled={state.disabled} onMouseEnter={() => setActionHover(true)} onMouseLeave={() => setActionHover(false)} style={{ border: \"1px solid \" + state.actionBorder, borderRadius: 12, padding: \"8px 16px\", background: actionHover ? state.actionHoverBg : state.actionBg, color: state.actionText, fontWeight: 800 }}>Primary action</button><button type=\"button\" disabled={state.disabled} style={{ border: \"1px solid \" + state.border, borderRadius: 12, padding: \"8px 16px\", background: \"transparent\", color: state.foreground, fontWeight: 800 }}>Secondary</button></div> : null}",
    "      </div>",
    "    </section>",
    "  );",
    "}",
    "",
  ].join("\n");
}
