import type { AlertState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: AlertState, fileName = "alert"): ExportPayload {
  return { fileName: `${fileName || "alert"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: AlertState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
    "",
    "const severityTone = {",
    "  info: { label: \"Information\", icon: \"i\", fallback: \"#38bdf8\" },",
    "  success: { label: \"Success\", icon: \"+\", fallback: \"#22c55e\" },",
    "  warning: { label: \"Warning\", icon: \"!\", fallback: \"#f59e0b\" },",
    "  error: { label: \"Error\", icon: \"!\", fallback: \"#fb7185\" },",
    "};",
    "",
    "export default function AlertComponent() {",
    "  const tone = severityTone[state.severity] || severityTone.info;",
    "  const accent = state.accent || tone.fallback;",
    "  const isAssertive = state.role === \"alert\" || state.livePoliteness === \"assertive\";",
    "  const isDismissed = state.previewState === \"closed\";",
    "",
    "  if (isDismissed) {",
    "    return <div role=\"status\" aria-live=\"polite\" style={{ border: \"1px solid \" + state.border, borderRadius: 16, color: state.muted, fontFamily: state.fontFamily, padding: \"12px 16px\" }}>Alert dismissed.</div>;",
    "  }",
    "",
    "  return (",
    "    <section",
    "      id={state.id}",
    "      role={state.role}",
    "      aria-label={state.ariaLabel}",
    "      aria-live={state.livePoliteness}",
    "      aria-atomic=\"true\"",
    "      tabIndex={state.disabled ? -1 : state.tabIndex}",
    "      data-severity={state.severity}",
    "      data-placement={state.placement}",
    "      style={{",
    "        width: state.width,",
    "        minHeight: state.height,",
    "        padding: state.padding,",
    "        borderRadius: state.radius,",
    "        border: state.borderWidth + \"px solid \" + state.border,",
    "        boxShadow: \"0 \" + Math.round(state.shadow / 3) + \"px \" + state.shadow + \"px rgba(0,0,0,.28)\",",
    "        background: state.background,",
    "        color: state.foreground,",
    "        fontFamily: state.fontFamily,",
    "        opacity: state.disabled ? 0.55 : 1,",
    "        transition: state.motion ? \"opacity 0.2s ease, transform 0.2s ease\" : \"none\",",
    "        transform: state.motion ? \"translateY(0)\" : undefined,",
    "      }}",
    "    >",
    "      <div style={{ display: \"grid\", gap: state.gap }}>",
    "        <div style={{ display: \"flex\", alignItems: \"flex-start\", gap: 16 }}>",
    "          {state.iconMode !== \"none\" ? <span aria-hidden=\"true\" style={{ display: \"grid\", placeItems: \"center\", width: 40, height: 40, flexShrink: 0, borderRadius: 16, border: \"1px solid \" + accent, color: accent, background: \"color-mix(in oklab, \" + accent + \" 16%, transparent)\", fontWeight: 900 }}>{tone.icon}</span> : null}",
    "          <div style={{ display: \"grid\", gap: 8, flex: 1, minWidth: 0 }}>",
    "            <p style={{ margin: 0, color: accent, fontSize: 12, fontWeight: 800, letterSpacing: \"0.16em\", textTransform: \"uppercase\" }}>{state.label || tone.label}</p>",
    "            <h3 style={{ margin: 0, fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h3>",
    "            <p style={{ margin: 0, color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "          </div>",
    "          {state.dismissible ? <button type=\"button\" aria-label=\"Dismiss alert\" disabled={state.disabled} style={{ border: \"1px solid \" + state.border, borderRadius: 12, padding: \"8px 12px\", background: \"transparent\", color: state.foreground }}>x</button> : null}",
    "        </div>",
    "        <p style={{ margin: 0, border: \"1px solid \" + state.border, borderRadius: 16, padding: \"12px 16px\", color: state.muted, fontSize: state.bodySize }}>{state.helper} {isAssertive ? \"Assertive announcement.\" : \"Polite announcement.\"}</p>",
    "        {state.showActions ? <div style={{ display: \"flex\", flexWrap: \"wrap\", gap: 12 }}><button type=\"button\" disabled={state.disabled} style={{ border: 0, borderRadius: 12, padding: \"8px 16px\", background: accent, color: \"#020617\", fontWeight: 800 }}>Primary action</button><button type=\"button\" disabled={state.disabled} style={{ border: \"1px solid \" + state.border, borderRadius: 12, padding: \"8px 16px\", background: \"transparent\", color: state.foreground, fontWeight: 800 }}>Secondary</button></div> : null}",
    "      </div>",
    "    </section>",
    "  );",
    "}",
    "",
  ].join("\n");
}
